-- copy the sched task from the table sched_task to the new quartz_sched_task, including the reported executions

insert into QUARTZ_SCHED_TASK_EXEC (TASK_ID, TASK_TYPE, EXEC_TIME, EXEC_STATUS_B, COMMENTS, END_TIME, VAL_TIME, TASK_EXEC_USER,  EXEC_STATUS)
select TASK_ID, TASK_TYPE, EXEC_TIME, EXEC_STATUS_B, COMMENTS, END_TIME, VAL_TIME, TASK_EXEC_USER, EXEC_STATUS_B from SCHED_TASK_EXEC;

insert into quartz_sched_task_attr (TASK_ID, ATTR_NAME, ATTR_VALUE, VALUE_ORDER)
select TASK_ID, ATTR_NAME, ATTR_VALUE, VALUE_ORDER from sched_task_attr;

insert into quartz_sched_task (COMMENTS,DATE_RULE_ID,DESCRIPTION,ENTERED_DATE,EXECUTE_B,EXEC_DS_B,EXEC_HOL,EXTERNAL_REF,FILTER_SET,FROM_DAYS,HOLIDAYS,IS_DEACTIVATED,NEXT_ID,PO_ID,PRICER_MEASURES,PRICING_ENV,PRIVATE_B,PUBLISH_B,READ_ONLY_SRVR_B,RISK_CFG_NAME,SCHED_TIME,SEND_EMAIL_B,SKIP_CUTOFF_TIME,SKIP_EXEC_B,TASK_ID,TASK_TYPE,TIME_ZONE,TO_DAYS,TRADE_FILTER,UNDO_TIME,USER_NAME,VALDATE_OFFSET,VAL_TIME,VERSION_NUM)
select COMMENTS,DATE_RULE_ID,DESCRIPTION,ENTERED_DATE,EXECUTE_B,EXEC_DS_B,EXEC_HOL,EXTERNAL_REF,FILTER_SET,FROM_DAYS,HOLIDAYS,IS_DEACTIVATED,NEXT_ID,PO_ID,PRICER_MEASURES,PRICING_ENV,PRIVATE_B,PUBLISH_B,READ_ONLY_SRVR_B,RISK_CFG_NAME,SCHED_TIME,SEND_EMAIL_B,SKIP_CUTOFF_TIME,SKIP_EXEC_B,TASK_ID,TASK_TYPE,TIME_ZONE,TO_DAYS,TRADE_FILTER,UNDO_TIME,USER_NAME,VALDATE_OFFSET,VAL_TIME,VERSION_NUM from sched_task;

-- add a per default sla of 5 minutes for each task
INSERT INTO QUARTZ_SCHED_TASK_ATTR (TASK_id, ATTR_NAME, ATTR_VALUE, VALUE_ORDER) SELECT TASK_ID, 'SLA_MINUTES', 5, 0 from QUARTZ_SCHED_TASK;

-- update the execution status
update QUARTZ_SCHED_TASK_EXEC set exec_status = 'success' where exec_status_b = 1;
update QUARTZ_SCHED_TASK_EXEC set exec_status = 'failed' where exec_status_b = 0;
